number of tweaks

diff --git a/zsh-functions/utils b/zsh-functions/utils
--- a/zsh-functions/utils
+++ b/zsh-functions/utils
@@ -1,20 +1,218 @@
-# Download and execute a bash script.
-function rex(){
-	sourceScriptUrl=$1
-	if [ ! ${sourceScriptUrl} ]; then
-		echo "You must specify the URL of the script to execute"
-		echo "Example:"
-		echo "	rex https://gist.githubusercontent.com/user/hash/raw/hash-2/script.sh"
-		exit 1
-	fi
-	curl -L ${sourceScriptUrl} | bash
+#! /usr/bin/env bash
+
+function cyan(){
+		echo "\033[0;36m"
+}
+
+function green(){
+		echo "\033[0;32m"
+}
+
+function red(){
+		echo "\033[0;31m"
+}
+
+function nocolor(){
+		echo "\033[0m"
 }
 
 # Open a file in Marked 2.
 function marked(){
-	if [ $1 ]; then
-    	open -a "Marked 2" $1;
-	else
-    	open -a "Marked 2";
-	fi
+		if [ $1 ]; then
+				open -a "Marked 2" $1;
+		else
+				open -a "Marked 2";
+		fi
+}
+
+# Creates the slug version of an input string.
+function slugify(){
+		echo -n "$@" | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z
+}
+
+# Batch rename all the files and directories in the current working directory to theirs slug version.
+# Requires the slugify function.
+function slugify-all(){
+		for f in $(pwd)/*; do
+				d="$(slugify $(basename $f))"; 
+				if [ $(pwd)/$d != $f ]; then 
+						mv $f $(pwd)/$d; 
+				fi; 
+		done
+}
+
+# Recursively renames all files and directoriesj in the current working directory to their slugified version.
+function recursive-slugify-all(){
+		slugify-all;
+		for d in $(pwd)/*/; do
+				echo "slugifying sub-dir $d"
+				(cd $d; recursive-slugify-all);
+		done
+}
+
+# Links the vendor version of a library with a directory from ~/Repos.
+function repo-link(){
+
+		if [[ -z "$1" ]]; then
+				echo ""
+				echo "Usage: $(green)repo-link <rep_rel_source> [<author/package>]$(nocolor)"
+				echo ""
+				echo "W/o specifying an author/package the package will be linked in $(green)vendor/lucatume/<package>$(nocolor) directory:"
+				echo "	$(green)repo-link repo $(nocolor)"
+				echo ""
+				echo "Specifying an author/package the package will be linked in $(green)vendor/<author>/<package>$(nocolor) directory:"
+				echo "	$(green)repo-link repo author/package$(nocolor)"
+				return -1
+		fi
+
+		source="${HOME}/Repos/$1"
+		dest="$(pwd)/vendor/${2:-"lucatume/$1"}"
+		echo "$(green)Source:$(nocolor) ${source}"
+		echo "$(green)Destination:$(nocolor) ${dest}"
+
+		if [[ ! -d "${source}" ]]; then
+				echo ""
+				echo "$(red)Repo directory ($source) does not exist!$(nocolor)"
+				return -1
+		fi
+		
+		if [[ -d "$dest" ]]; then
+				echo ""
+				echo "$(green)Destination directory (${dest}) exists."
+				echo ""
+				echo -ne "$(cyan)Would you like to replace it with a symbolic link to the repo directory (y/n)?$(nocolor) "
+				read replace
+
+				if [[ "${replace}" =~ ^n  ]]; then
+						echo ""
+						echo "Ok, no symbolic link created."
+						return 0
+				else
+						echo ""
+						echo "$(green)Removing the '${dest}' directory...$(nocolor)"
+
+						rm -rf "$dest"
+
+						if [[ $? != 0 ]]; then
+								echo ""
+								echo "$(red)Could not remove the '${dest} directory.'$(nocolor)"
+								return -1
+						fi
+				fi
+		elif [[ ! -d "$(dirname (${dest}))" ]];then
+				echo ""
+				echo "$(green)Destination directory parent ($(dirname ${dest})) does not exist."
+				echo ""
+				echo -ne "$(cyan)Would you like to create it (y/n)?$(nocolor) "
+				read create
+
+				if [[ ${create} =~ ^y ]]; then
+						echo ""
+						echo "Creating the '$(dirname ${dest})' directory..."
+						mkdir -p "$(dirname ${dest})"
+
+						if [[ $? != 0 ]]; then
+								return -1
+						fi
+				fi
+		fi
+
+		echo ""
+		echo "Creating symbolic link between: '${source}' and '${dest}'"
+		echo ""
+
+		ln -s "${source}" "${dest}"
+
+		if [[ $? != 0 ]]; then
+				return -1
+		fi
+
+		echo "All done."
+		echo ""
+
+		tree -L 2 -l -C "$(dirname ${dest})"
+}
+
+# Rsyncs the vendor version of a library with a directory from ~/Repos.
+function repo-sync(){
+
+		if [[ -z "$1" ]]; then
+				echo ""
+				echo "Usage: $(green)repo-sync <rep_rel_source> [<author>]$(nocolor)"
+				echo ""
+				echo "W/o specifying an author the package will be synced in $(green)vendor/lucatume/<repo>$(nocolor) directory:"
+				echo "	$(green)repo-link repo $(nocolor)"
+				echo ""
+				echo "Specifying an author the package will be synced in $(green)vendor/<author>/<repo>$(nocolor) directory:"
+				echo "	$(green)repo-link repo author$(nocolor)"
+				return -1
+		fi
+
+		source="${HOME}/Repos/$1"
+		dest="$(pwd)/vendor/${2:-lucatume}"
+		echo "$(green)Source:$(nocolor) ${source}"
+		echo "$(green)Destination:$(nocolor) ${dest}"
+
+		if [[ ! -d "${source}" ]]; then
+				echo ""
+				echo "$(red)Repo directory ($source) does not exist!$(nocolor)"
+				return -1
+		fi
+
+		if [[ ! -d "${dest}" ]]; then
+				echo ""
+				echo "$(green)Parent directory '${dest}' does not exist.$(nocolor)"
+				echo "$(cyan)Would you like to create it? (y/n)$(nocolor) "
+				read create
+
+				if [[ ${create} =~ ^y ]]; then
+						echo ""
+						echo "Creating the '${dest}' directory..."
+						mkdir -p "${dest}"
+
+						if [[ $? != 0 ]]; then
+								return -1
+						fi
+				fi
+		elif [[ -L "${dest}/$1" ]]; then
+				echo ""
+				echo "$(green)Directory '${dest}/$1' is a symbolic link.$(nocolor)"
+				echo "$(cyan)Would you like to remove it? (y/n)$(nocolor) "
+				read remove
+
+				if [[ $remove =~ ^y ]]; then
+						echo ""
+						echo "$(green)Removing the '${dest}/$1' directory...$(nocolor)"
+
+						rm -rf "$dest/$1"
+
+						if [[ $? != 0 ]]; then
+								echo ""
+								echo "$(red)Could not remove the '${dest}/$1' directory.'$(nocolor)"
+								return -1
+						fi
+				else
+						echo ""
+						echo "$(green)Ok, destination directory '${dest}/$1' not removed.$(nocolor)"
+						return 0
+				fi
+		fi
+
+		echo ""
+		echo "RSyncing: '${source}' to '${dest}/$1'..."
+		echo ""
+
+		rsync -aE "$source" "$dest"
+
+		echo ""
+
+		if [[ $? == 0 ]]; then
+				echo "Done."
+		else
+				echo "$(red)Something went wrong, see the error above.$(nocolor)"
+		fi
+
+		tree -L 2 -C "${dest}"
+	
+		return $?
 }
